
server:
    port: 8084

management:
    server:
        port: 8094
        address: tuannt.com
    endpoints:
        web:
            base-path: /management
            exposure:
                include: ["configprops", "env", "health", "info", "metrics", "mappings", "sessions", "shutdown", "threaddump"]
    endpoint:
        shutdown:
            enabled: true
